#!/bin/sh

. ./setup-env

if [ ! -f $EV3DEV_INSTALL ]
then
        mkdir -p $EV3DEV_INSTALL || exit $?
fi

mkimage -A arm -O linux -T script -C none -a 0 -e 0 -n "ev3dev" -d boot.cmd $EV3DEV_INSTALL/boot.scr

