#!/bin/sh -e

function usage() {
	echo "usage: ./create-image"
	echo
	echo "ENVIRONMENT VARIABLES"
	echo "---------------------"
	echo "DEBIAN_MIRROR    URL for debian package repository"
	echo "                 default: http://ftp.debian.org/debian"
	echo "EV3DEV_MIRROR    URL for ev3dev package repository"
	echo "                 default: http://ppa.lechnology.com/ev3dev"
	exit 0
}

if [ ! -z $DEBIAN_MIRROR ]; then
	DEBIAN_MIRROR="-m $DEBIAN_MIRROR"
fi

while [[ $# > 0 ]]; do
	opt="$1"
	shift

	case $opt in
	-f|--force)
		force=1
		;;
	-h|-?|--help)
		usage
		exit 0
		;;
	*)
		;;
	esac
done

if [ force || ! -d ev3dev-rootfs ]; then
    polystrap -f -d ev3dev-rootfs $DEBIAN_MIRROR ev3dev
fi

# guestfish does not know how to set label for vfat!

guestfish -N bootrootlv:/dev/vg0/lv0:vfat:ext3:500M:48M:mbr \
part-set-mbr-id /dev/sda 1 0x0b : \
set-label /dev/vg0/lv0 EV3_FILESYS : \
mount /dev/vg0/lv0 / : \
tar-in ev3dev-rootfs.tar.gz / compress:gzip : \
mkdir-p /media/mmc_p1 : \
mount /dev/sda1 /media/mmc_p1 : \
mv /uImage /media/mmc_p1/ : \
mv /uInitrd /media/mmc_p1/ : \
mv /boot.scr /media/mmc_p1/ : \
mv /ev3dev.rc.local /media/mmc_p1/

# Hack to set the volume label on the vfat partition since guestfish does not know how
# volume name must be null padded to exactly 11 bytes
echo -e "EV3_BOOT\0\0\0" | dd of=test1.img bs=1 seek=32811 count=11 conv=notrunc

mv test1.img ev3dev.img
zip -9 ev3dev.img.zip ev3dev.img
cat ev3dev.img | xz -9 > ev3dev.img.xz
